### ISSUE TITLE
`Uncaught SyntaxError` in browser console when using plugin for storybook

### ISSUE THREAD

**Issue by ainalain** [strothj/react-docgen-typescript-loader#1] opened 2018-02-09 22:39 UTC
Hi, thank you for this plugin, I understand that this project was written quick and dirty, the idea is very cool!
 
At work, I use typescript and storybook for React components. I added **react-docgen-typescript-webpack-plugin** to my .storybook **webpack.config.js** because I wanted to use the power of Storybook Info Addon and to have the prop types displayed in the rendered story. Unfortunately, with plugin added to webpack.config.js file, storybook fails in the browser with error
**Uncaught SyntaxError: Unexpected identifier** (very javascripty)
There is a screenshot of this state but I guess it isn't very verbose 😞

<img width="990" alt="screen shot 2018-02-10 at 01 19 31" src="https://user-images.githubusercontent.com/16562120/36053196-c43ff012-0e01-11e8-9c1b-147afe010514.png">

So I'll try to solve the problem next week but if you'll face it in your development, could you please explain the error here.

**Comment by strothj** [comment] 2018-02-10 01:52
So there were two issues:

* Multi-line description strings were not being escaped properly.
* Multiple props were not having a comma added as a separator.

Can you try version 1.0.1 and see if that fixes your issue?

**Comment by tsiq-swyx** [comment] 2018-02-10 11:02
hello! i am using 1.0.1. now the issue is `Uncaught SyntaxError: Unexpected token -`

![image](https://user-images.githubusercontent.com/35976578/36061415-ee0721b0-0e27-11e8-9f44-71da1de27409.png)

and the source of it seems to be this JS code: 
![image](https://user-images.githubusercontent.com/35976578/36061420-ff549952-0e27-11e8-81e9-b118b348fb3b.png)

**Comment by strothj** [comment] 2018-02-10 17:45
@tsiq-swyx I was able to reproduce the issue. Can you try v1.0.2?

**Comment by tsiq-swyx** [comment] 2018-02-10 18:32
yes, and it was totally fixed. wow!

**Comment by ainalain** [comment] 2018-02-10 22:06
@strothj my `Unexpected identifier` was related to importing from "react-select":
```
...
import Select, {  ReactSelectProps } from "react-select";
```
And there are 2 members of `ReactSelectProps` interface that are causing the error:
1. 
```
 /**
   * Message to use for screenreaders to press backspace to remove the current item
   * {label} is replaced with the item label
   * @default "Press backspace to remove..."
   */
    backspaceToRemoveMessage?: string;
```
2.
```
 /**
   * whether the Select is loading externally or not (such as options being loaded).
   * if true, a loading spinner will be shown at the right side.
   * @default false
   */
    isLoading?: boolean;
```

I don't know why these annotations are compiled without closing quote:
<img width="1339" alt="screen shot 2018-02-11 at 01 03 25" src="https://user-images.githubusercontent.com/16562120/36067098-72675142-0ec7-11e8-96b3-2ca6303b70be.png">

<img width="1276" alt="screen shot 2018-02-11 at 01 05 05" src="https://user-images.githubusercontent.com/16562120/36067106-acf9eea0-0ec7-11e8-8bfa-feb2626531a8.png">

**Comment by strothj** [comment] 2018-02-11 05:15
@ainalain Are you still having this problem with v1.0.2 ? I think this was related to not escaping the new lines in description text which I believe is fixed.

**Comment by ainalain** [comment] 2018-02-11 11:41
@strothj Yes, unfortunately, v1.0.2 didn't help.

**Comment by strothj** [comment] 2018-02-11 11:48
I didn't encounter these sorts of problems with the Babel plugin I developed since it was operating on the AST.

I think I will need to investigate another place to hook into the pipeline to gain access to the original TypeScript source. Right now I'm only getting access to the post compiled output from ts-loader. I think generating the code snippet as an AST will prevent issues with strings having line breaks, etc.

I will need to investigate further.

**Comment by ainalain** [comment] 2018-02-11 11:53
I understand. It would be cool to have all documentation tools provided by storybook but I know that typescript always adds extra challenge.

**Comment by strothj** [comment] 2018-02-11 12:11
Yep, I plan to look at this again soon. I'm working to know out a milestone for a client's project at the moment. As soon as that's done I'll be taking a deep dive into it.

**Comment by strothj** [comment] 2018-02-12 12:38
Hello, I have begun work on code transformation at the original source code level. This will allow inserting the generated code before it is compiled by Webpack. This should resolve the `esnext` module target issue. The line wrapping issue will be resolved through the use of AST to generate the code instead of string interpolation.

Tracking this on #3

**Comment by strothj** [comment] 2018-02-15 23:35
Closing as it is addressed by plugin.

**Closed by strothj** 2018-02-15 23:35 UTC
